# Generated by Django 5.0.7 on 2024-10-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_smile', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.BinaryField()),
                ('mol2vec', models.BinaryField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='virtual_scr_id_c7a08c_idx'), models.Index(fields=['created_at'], name='virtual_scr_created_15af98_idx')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_name', models.CharField(max_length=255)),
                ('receptor_file', models.FileField(upload_to='receptor_files/')),
                ('result_directory', models.CharField(max_length=500)),
                ('score_1', models.FloatField(blank=True, null=True)),
                ('score_2', models.FloatField(blank=True, null=True)),
                ('score_3', models.FloatField(blank=True, null=True)),
                ('score_4', models.FloatField(blank=True, null=True)),
                ('score_5', models.FloatField(blank=True, null=True)),
                ('score_6', models.FloatField(blank=True, null=True)),
                ('score_7', models.FloatField(blank=True, null=True)),
                ('score_8', models.FloatField(blank=True, null=True)),
                ('score_9', models.FloatField(blank=True, null=True)),
                ('score_10', models.FloatField(blank=True, null=True)),
                ('search_method', models.CharField(max_length=100)),
                ('execution_time', models.FloatField(help_text='Time taken for searching (in seconds)')),
                ('status', models.CharField(choices=[('successed', 'Successed'), ('failed', 'Failed')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('ligand_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_1', to='virtual_screening.ligand')),
                ('ligand_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_10', to='virtual_screening.ligand')),
                ('ligand_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_2', to='virtual_screening.ligand')),
                ('ligand_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_3', to='virtual_screening.ligand')),
                ('ligand_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_4', to='virtual_screening.ligand')),
                ('ligand_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_5', to='virtual_screening.ligand')),
                ('ligand_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_6', to='virtual_screening.ligand')),
                ('ligand_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_7', to='virtual_screening.ligand')),
                ('ligand_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_8', to='virtual_screening.ligand')),
                ('ligand_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligand_9', to='virtual_screening.ligand')),
            ],
            options={
                'indexes': [models.Index(fields=['receptor_name'], name='virtual_scr_recepto_367c86_idx'), models.Index(fields=['status'], name='virtual_scr_status_c30402_idx')],
            },
        ),
    ]
