# Generated by Django 5.0.7 on 2024-09-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ligand',
            index=models.Index(fields=['id'], name='virtual_scr_id_c7a08c_idx'),
        ),
        migrations.AddIndex(
            model_name='ligand',
            index=models.Index(fields=['created_at'], name='virtual_scr_created_15af98_idx'),
        ),
    ]
