version: "3.9"

services:
    app:
        image: "ligand_search:latest"
        platform: linux/amd64
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - ../2M/data:/screening/data
            - ../2M/method:/screening/method
            - ../2M/result:/screening/result
        command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
